@node Thanks
@unnumbered Thanks

Thanks for contributions and suggestions to:

@itemize
@item Bruce Schneier for his @url{https://www.schneier.com/books/applied_cryptography/, Applied Cryptography}.
@item Watson Ladd for suggestion of @url{http://elligator.cr.yp.to/, Elligator} encoding.
@item Zhuoyun Wei for @url{https://aur.archlinux.org/packages/govpn/, AUR} port maintaining and his documentation related fixes.
@end itemize
